### ISSUE TITLE
MacOS - etesync-dav - "Wrong password for user." error

### ISSUE THREAD

**Issue by flewid** [etesync/etesync-dav#262]
Hello, 

I am self hosting etesync on my server. Followed all the step to set it up. 

When logging in through the web interface (https://pim.etesync.com/pim/contacts) everything works. 

However, when trying to setup etesync-dav on my local machine I receive an error. 

I run the app with -D to get debug info 

then hit http://localhost:37358/

I enter 

user: username i created on server
password: same password i used on account creation
url: https://my.server.com 

then I receive "Wrong password for user." 

I know the password is correct as it works fine through pim.etesync.com using the same URL. 

The debug log displays this, which isn't super helpful;'

```
[2022-04-06 13:55:17 -0400] [82595/Thread-15] [DEBUG] Sanitized script name: ''
[2022-04-06 13:55:17 -0400] [82595/Thread-15] [DEBUG] Sanitized path: '/favicon.ico'
[2022-04-06 13:55:17 -0400] [82595/Thread-15] [INFO] Access to '/favicon.ico' denied for anonymous user
[2022-04-06 13:55:17 -0400] [82595/Thread-15] [DEBUG] Asking client for authentication
[2022-04-06 13:55:17 -0400] [82595/Thread-15] [DEBUG] Response content:
Access to the requested resource forbidden.
[2022-04-06 13:55:17 -0400] [82595/Thread-15] [INFO] GET response status for '/favicon.ico' in 0.002 seconds: 401 Unauthorized
[2022-04-06 13:55:23 -0400] [82595/Thread-16] [INFO] POST request for '/.web/add/' received from ::1 using 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Safari/537.36'
[2022-04-06 13:55:23 -0400] [82595/Thread-16] [DEBUG] Request headers:
{'CONTENT_LENGTH': '311',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'en-GB,en-US;q=0.9,en;q=0.8',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': '**masked**',
 'HTTP_HOST': 'localhost:37358',
 'HTTP_ORIGIN': 'http://localhost:37358',
 'HTTP_REFERER': 'http://localhost:37358/.web/add/',
 'HTTP_SEC_FETCH_DEST': 'document',
 'HTTP_SEC_FETCH_MODE': 'navigate',
 'HTTP_SEC_FETCH_SITE': 'same-origin',
 'HTTP_SEC_FETCH_USER': '?1',
 'HTTP_SEC_GPC': '1',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/99.0.4844.88 Safari/537.36',
 'PATH_INFO': '/.web/add/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa',
 'SERVER_PORT': '37358',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=9>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2022-04-06 13:55:23 -0400] [82595/Thread-16] [DEBUG] Sanitized script name: ''
[2022-04-06 13:55:23 -0400] [82595/Thread-16] [DEBUG] Sanitized path: '/.web/add/'
Logging in
[2022-04-06 13:55:24 -0400] [82595/Thread-16] [INFO] POST response status for '/.web/add/' in 1.402 seconds: 200 OK
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [INFO] GET request for '/favicon.ico' received from ::1 using 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Safari/537.36'
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [DEBUG] Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'en-GB,en-US;q=0.9,en;q=0.8',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': '**masked**',
 'HTTP_HOST': 'localhost:37358',
 'HTTP_REFERER': 'http://localhost:37358/.web/add/',
 'HTTP_SEC_FETCH_DEST': 'image',
 'HTTP_SEC_FETCH_MODE': 'no-cors',
 'HTTP_SEC_FETCH_SITE': 'same-origin',
 'HTTP_SEC_GPC': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/99.0.4844.88 Safari/537.36',
 'PATH_INFO': '/favicon.ico',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa',
 'SERVER_PORT': '37358',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=9>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [DEBUG] Sanitized script name: ''
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [DEBUG] Sanitized path: '/favicon.ico'
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [INFO] Access to '/favicon.ico' denied for anonymous user
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [DEBUG] Asking client for authentication
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [DEBUG] Response content:
Access to the requested resource forbidden.
[2022-04-06 13:55:24 -0400] [82595/Thread-17] [INFO] GET response status for '/favicon.ico' in 0.001 seconds: 401 Unauthorized
```

**Comment by flewid** [comment]
Oddly enough, I also just tried installing it on my qnap nas through constainer station using docker. And I still receive the 'wrong password for user' error

**Comment by tasn** [comment]
The instructions can be a bit confusing, but there are multiple passwords.
The main page though should use the account password (same as pim.etesync.com) so not sure what's going on.

**Comment by flewid** [comment]
Yep - understand that once i sign in through localhost, it'll give me a different password that I use from my local apps - is that right?

**Comment by flewid** [comment]
Also, do you have a docker compose script handy so I can install this on the NAS separately and access from any computer on the lan?

**Comment by tasn** [comment]
Happy to accept a PR for adding a docker compose, but nothing at the moment.

**Comment by flewid** [comment]
Okay I've gotten it working with Docker using this compose

```
######## 
# etesync-dav
########

version: "3"
services:
  etesync:
    image: etesync/etesync-dav
    container_name: etesync
    environment:
      - PUID=1002
      - PGID=100
      - TZ=America/Toronto
      - ETESYNC_DATA_DIR=/data
      - ETESYNC_SERVER_HOSTS=0.0.0.0:37358,[::]:37358
      - GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
      - LANG=C.UTF-8
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PYTHON_GET_PIP_SHA256=6665659241292b2147b58922b9ffe11dda66b39d52d8a6f3aa310bc1d60ea6f7
      - PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/a1675ab6c2bd898ed82b1f58c486097f763c74a9/public/get-pip.py
      - PYTHON_PIP_VERSION=21.1.3
      - PYTHON_VERSION=3.8.11
    volumes:
      - /share/Configs/docker/etesync-dav:/config
    ports:
          - 37358:37358
    restart: unless-stopped
```

However, I still have the "Wrong password for user. " error. 

Just to run through what I've done; 

1. Installed etesync on my server w/ apache + ssl 
2. logged into the admin and created a user 
3. Connected to it from your website, created a password 
4. All works fine (I can import calendars, contacts, edit, etc) 
5. Then I run the -dav daemon, connect and input the same password I use to connect through the web interface 

Am I using the wrong password or something?
