### ISSUE TITLE
Docker Image will not work behind Proxy

### ISSUE THREAD

**Issue by SvartrShell** [etesync/etesync-dav#347]
Having an issue getting this to work behind my reverse proxy - no matter what combo of ETESYNC_SERVER_HOSTS i put i get errors 

```
  etesync-dav:
    container_name: etesync-dav
    image: etesync/etesync-dav:latest
    restart: always
    environment:
      ETESYNC_LISTEN_ADDRESS: 0.0.0.0
      ETESYNC_SERVER_HOSTS: 'host.domain.com,DOCKER_IP_ADD'
    ports:
      - "37358:37358"
    volumes:
      - "etesync-dav:/data"
```

gives error 
`[2025-04-09 09:57:12 +0000] [1] [CRITICAL] Invalid configuration: Invalid list_of_ip_address value for option 'hosts' in section 'server' in arguments: 'host.domain.com,DOCKER_IP_ADD'`

I have tried all combos, adding port 443 to the host name, removing it entirely - nothing works - it used to - but i recently updated and it stopped working
